const Event = require('../models/Event')

async function initializeEvents() {
  try {
    const existingCount = await Event.countDocuments()
    if (existingCount > 0) {
      console.log('✅ Events already exist in database')
      return
    }

    const eventsData = [
      // Upcoming Events
      {
        eventId: 'e1',
        type: 'Workshop',
        featured: true,
        status: 'Open',
        isPast: false,
        title: 'Arduino for Absolute Beginners',
        sub: 'Build your first circuit and program your first robot in one day.',
        desc: "Dive straight into electronics and microcontrollers. You'll wire components, read sensors, and write real C++ code — then take your project home.",
        day: '18',
        month: 'JUL',
        year: '2026',
        monthFull: 'July 2026',
        time: '10:00 AM – 4:00 PM',
        duration: '6 Hours',
        venue: 'Nimo Labs HQ, Bhopal',
        seats: 20,
        filled: 13,
        target: new Date('2026-07-18T10:00:00'),
        tags: ['Beginner Friendly', 'Take-Home Kit', 'Certificate'],
        price: '₹999',
        num: '01',
        order: 0,
      },
      {
        eventId: 'e2',
        type: 'Summer Camp',
        featured: false,
        status: 'Filling Fast',
        isPast: false,
        title: 'Robotics Summer Camp 2026',
        sub: '5 immersive days — build 3 robots, code, compete.',
        desc: 'The flagship summer experience. Students build a line follower, obstacle avoider, and freestyle robot, then compete in a final showcase.',
        day: '02',
        month: 'AUG',
        year: '2026',
        monthFull: 'August 2026',
        time: '9:00 AM – 5:00 PM',
        duration: '5 Days',
        venue: 'Nimo Labs HQ, Bhopal',
        seats: 40,
        filled: 28,
        target: new Date('2026-08-02T09:00:00'),
        tags: ['Ages 10–18', '3 Robots', 'Certificate'],
        price: '₹3,499',
        num: '02',
        order: 1,
      },
      {
        eventId: 'e3',
        type: 'Workshop',
        featured: false,
        status: 'Open',
        isPast: false,
        title: 'ESP32 & IoT Masterclass',
        sub: 'Build connected devices and deploy to the cloud.',
        desc: 'For students who know Arduino basics. Covers Wi-Fi, MQTT, cloud dashboards, and real sensor deployments on ESP32.',
        day: '22',
        month: 'JUL',
        year: '2026',
        monthFull: 'July 2026',
        time: '10:00 AM – 5:00 PM',
        duration: '7 Hours',
        venue: 'Nimo Labs HQ, Bhopal',
        seats: 15,
        filled: 5,
        target: new Date('2026-07-22T10:00:00'),
        tags: ['Intermediate', 'Cloud Dashboards', 'Take-Home'],
        price: '₹1,299',
        num: '03',
        order: 2,
      },
      {
        eventId: 'e4',
        type: 'School Visit',
        featured: false,
        status: 'Booking Open',
        isPast: false,
        title: 'Robotics Demo at Your Campus',
        sub: 'We bring live robots to your school or college.',
        desc: 'A 2–3 hour immersive demo session — live robots, coding intro, and a hands-on challenge for the class. Flexible scheduling, any day.',
        day: 'ANY',
        month: 'DATE',
        year: '2026',
        monthFull: 'Flexible',
        time: 'Flexible',
        duration: '2–3 Hours',
        venue: 'Your School / College',
        seats: 999,
        filled: 0,
        target: null,
        tags: ['All Ages', 'Free Consultation', 'Custom Schedule'],
        price: 'Contact Us',
        num: '04',
        order: 3,
      },
      {
        eventId: 'e5',
        type: 'Competition',
        featured: false,
        status: 'Coming Soon',
        isPast: false,
        title: 'NimoBot Challenge 2026',
        sub: 'Inter-school robot battle — speed, accuracy, creativity.',
        desc: 'Three categories: Line Follower Speed Run, Obstacle Course, and Freestyle Build. Open to all school and college teams. Cash prizes for top 3.',
        day: '15',
        month: 'AUG',
        year: '2026',
        monthFull: 'August 2026',
        time: '9:00 AM – 6:00 PM',
        duration: 'Full Day',
        venue: 'TBA — Bhopal City',
        seats: 60,
        filled: 0,
        target: new Date('2026-08-15T09:00:00'),
        tags: ['Teams of 3', 'Cash Prizes', 'All Schools'],
        price: '₹499 / team',
        num: '05',
        order: 4,
      },
      {
        eventId: 'e6',
        type: 'Workshop',
        featured: false,
        status: 'Open',
        isPast: false,
        title: '3D Design & Printing Bootcamp',
        sub: 'Design your own robot part — then print it.',
        desc: 'Learn Fusion 360 basics, design a custom robot enclosure or chassis part, and take the physical 3D print home at the end of the session.',
        day: '12',
        month: 'JUL',
        year: '2026',
        monthFull: 'July 2026',
        time: '10:00 AM – 3:00 PM',
        duration: '5 Hours',
        venue: 'Nimo Labs HQ, Bhopal',
        seats: 12,
        filled: 3,
        target: new Date('2026-07-12T10:00:00'),
        tags: ['Intermediate', 'Physical Takeaway', 'Software Included'],
        price: '₹1,499',
        num: '06',
        order: 5,
      },
      // Past Events
      {
        eventId: 'p1',
        type: 'Workshop',
        featured: false,
        status: 'Open',
        isPast: true,
        title: 'Arduino Day 2024',
        sub: 'Learn Arduino basics',
        desc: 'A hands-on workshop introducing students to Arduino microcontrollers and basic circuit design.',
        day: '15',
        month: 'MAR',
        year: '2024',
        monthFull: 'March 2024',
        time: 'All Day',
        duration: 'Workshop',
        venue: 'Nimo Labs HQ',
        seats: 50,
        filled: 45,
        target: null,
        tags: [],
        price: 'Free',
        num: '01',
        attendees: 45,
        highlight: 'Sold out in 48 hours',
        order: 6,
      },
      {
        eventId: 'p2',
        type: 'Summer Camp',
        featured: false,
        status: 'Open',
        isPast: true,
        title: 'Robotics Summer Camp',
        sub: 'Summer learning experience',
        desc: 'An immersive 5-day summer camp where students built 3 complete robots and learned programming fundamentals.',
        day: '10',
        month: 'JUN',
        year: '2024',
        monthFull: 'June 2024',
        time: 'All Day',
        duration: 'Camp',
        venue: 'Nimo Labs HQ',
        seats: 40,
        filled: 38,
        target: null,
        tags: [],
        price: '₹3,499',
        num: '02',
        attendees: 38,
        highlight: '38 students, 6 robots built',
        order: 7,
      },
      {
        eventId: 'p3',
        type: 'School Visit',
        featured: false,
        status: 'Open',
        isPast: true,
        title: 'Circuit Tour — 8 Schools',
        sub: 'School circuit tour',
        desc: 'Visited 8 schools across the city, introducing over 300 students to the world of robotics and electronics.',
        day: '05',
        month: 'AUG',
        year: '2024',
        monthFull: 'August 2024',
        time: 'All Day',
        duration: 'Tour',
        venue: 'Multiple Schools',
        seats: 320,
        filled: 320,
        target: null,
        tags: [],
        price: 'Free',
        num: '03',
        attendees: 320,
        highlight: '320 students across 8 schools',
        order: 8,
      },
      {
        eventId: 'p4',
        type: 'Competition',
        featured: false,
        status: 'Open',
        isPast: true,
        title: 'NimoBot Challenge 2024',
        sub: 'Robot competition',
        desc: 'The flagship robotics competition featuring 18 teams competing across 3 categories in line-following and obstacle avoidance.',
        day: '21',
        month: 'SEP',
        year: '2024',
        monthFull: 'September 2024',
        time: 'All Day',
        duration: 'Competition',
        venue: 'Bhopal City',
        seats: 60,
        filled: 60,
        target: null,
        tags: [],
        price: '₹499',
        num: '04',
        attendees: 120,
        highlight: '18 teams, 3 categories',
        order: 9,
      },
      {
        eventId: 'p5',
        type: 'Workshop',
        featured: false,
        status: 'Open',
        isPast: true,
        title: 'Sensors & Actuators WS',
        sub: 'Workshop on sensors',
        desc: 'Hands-on workshop covering practical sensor selection, calibration, and integration techniques for robotics projects.',
        day: '12',
        month: 'NOV',
        year: '2024',
        monthFull: 'November 2024',
        time: 'All Day',
        duration: 'Workshop',
        venue: 'Nimo Labs HQ',
        seats: 30,
        filled: 28,
        target: null,
        tags: [],
        price: 'Free',
        num: '05',
        attendees: 28,
        highlight: 'Fully hands-on, 0% lecture',
        order: 10,
      },
      {
        eventId: 'p6',
        type: 'Workshop',
        featured: false,
        status: 'Open',
        isPast: true,
        title: 'Python for Makers',
        sub: 'Python programming',
        desc: 'Introduction to Python specifically for hardware automation and robotics, with emphasis on GPIO and sensor libraries.',
        day: '14',
        month: 'DEC',
        year: '2024',
        monthFull: 'December 2024',
        time: 'All Day',
        duration: 'Workshop',
        venue: 'Nimo Labs HQ',
        seats: 25,
        filled: 22,
        target: null,
        tags: [],
        price: 'Free',
        num: '06',
        attendees: 22,
        highlight: 'Pi-powered automation demos',
        order: 11,
      },
    ]

    await Event.insertMany(eventsData)
    console.log('✅ Events initialized successfully!')
    console.log(`📅 Created ${eventsData.length} events (6 upcoming, 6 past)`)
  } catch (error) {
    console.error('❌ Error initializing events:', error.message)
  }
}

module.exports = initializeEvents
